name: Release Creation
description: Compresses images and creates zip artifact for release

on:
  workflow_call:
    inputs:
      tag_name: 
        description: 'The release tag we upload to'
        required: false
        type: string
jobs:
  image_resize_and_release:
    name: Image Resize Job
    runs-on: ubuntu-latest
    steps:
     - name: checkout
       uses: actions/checkout@v4
     - name: Install LibVips
       run: sudo apt install libvips-tools
     - name: Resize all images in-place
       run:  |
         shopt -s globstar
         vipsthumbnail ** --size 1300x2600
         for f in **/tn_*; do mv "$f" "$(echo "$f" | sed s/tn_//)"; done
     - name: Create release zip
       run: |
          zip -r protocol.zip
     - name: Upload release ZIP
       uses: softprops/action-gh-release@v2
       with:
          files: protocol.zip
          tag_name: tag_name
