name: Release Creation
description: Compresses images and creates zip artifact for release

inputs:
  tag_name: 
    description: 'The release tag we upload to'
    required: false
    type: string

runs:
  using: "composite"
  steps:
   - name: checkout
     uses: actions/checkout@v4
   
   - name: Install LibVips
     run: sudo apt install libvips-tools
     shell: bash
   
   - name: Resize all images in-place
     continue-on-error: true
     run: |
       shopt -s globstar
       vipsthumbnail ** --size 1300x2600
       for f in **/tn_*; do mv "$f" "$(echo "$f" | sed s/tn_//)"; done
     shell: bash
   
   - name: Create release zip
     run: |
        zip -r protocol.zip .
     shell: bash
   
   - name: Upload release ZIP
     uses: softprops/action-gh-release@v2
     with:
        files: protocol.zip
        tag_name: ${{ inputs.tag_name }}
