name: Release Creation
description: Compresses images and creates zip artifact for release

inputs:
  tag_name: 
    description: 'The release tag we upload to'
    required: false
    type: string

  src_directory: 
    description: 'The directory to zip attached to release'
    required: false
    type: string
    default: 'src'

runs:
  using: "composite"
  steps:
   - name: checkout
     uses: actions/checkout@v4

  - name: Change to source directory
     run: cd ./${{src_directory}}
     shell: bash

   - name: Install LibVips
     run: sudo apt install libvips-tools rename
     shell: bash

   - name: Resize all images using default names
     continue-on-error: true # if vipsthumbnail hits a non-image file it will exit with code 255; continue-on-error ignores this. 
     run: |
       shopt -s globstar
       vipsthumbnail ** --size 1300x2600
     shell: bash

   - name: Rename resized images
     run: find . -type f -name tn_* -exec rename -f -d 's/tn_//' {} \;
     shell: bash

   - name: Create release zip
     run: zip -r protocol.zip .
     shell: bash

   - name: Upload release ZIP
     uses: softprops/action-gh-release@v2
     with:
        files: protocol.zip
        tag_name: ${{ inputs.tag_name }}
